### ISSUE TITLE
[ Future request ] Test world option

### ISSUE THREAD

**Issue by JackYevhen** [Jaffe2718/Socket-Injection-Debugger#13]
just adding `test world` option in main menu, witch will automatically create a void world with platform, creative, command on, and other settings to hop right into making, and don't spend like 2min configuring the world to create

**Comment by Jaffe2718** [comment]
Enabling the IDEA plugin to create a Minecraft world would require introducing a lot of NBT editing libraries that would bloat the project. And automatically running the world would require launcher-like functionality, or embedding the launcher inside this IDEA plugin, which doesn't make sense since this plugin doesn't provide any launcher functionality.

**Comment by JackYevhen** [comment]
No, I mean in mod. (In minecraft)

**Comment by Jaffe2718** [comment]
This seems to be a function of world generation and presupposition, which seems to have nothing to do with the design concept of this mod, my mod is simply using socket to accept external to debug command and datapack.
